---
- set_fact:
    customrole_template: "{{ customrole_path | default('userrole.json.j2') }}"

- name: Create role
  uri: 
    url: "{{ api_base_url }}/{{ api_operations['add']['role'] }}"
    user: "{{ opdk_admin_email }}"
    password: "{{ opdk_admin_password }}"
    method: POST
    force_basic_auth: yes
    body: "{{ lookup('template', 'role.json.j2') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 201,409 

- name: Create role permissions
  uri: 
    url: "{{ api_base_url }}/{{ api_operations['add']['resourcepermissions'] }}"
    user: "{{ opdk_admin_email }}"
    password: "{{ opdk_admin_password }}"
    method: POST
    force_basic_auth: yes
    body: "{{ lookup('template', customrole_template) }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 201,409 