---
- name: ZK -> ZK port connectivity status  
  shell: |
    PASS=`nmap -Pn {{ hostvars[item.0].ansible_host }} -p {{  zookeeper_ports[item.1] }}|awk -F'/' '/filtered/ {print $1}'`;
    if [ ${PASS} -eq {{ zookeeper_ports[item.1] }} ]; then 
      RESULT="false"
    else
      RESULT="true"
    fi
    echo "{{ ansible_host }},{{ hostvars[item.0].ansible_host }},{{ item.0 }},{{ zookeeper_ports[item.1] }},$RESULT" 
  register: zookeeper_port_status
  ignore_errors: yes
  with_nested:
    - "{{ groups['ds'] | difference([inventory_hostname]) }}"
    - "{{ zookeeper_ports }}"

- name: Set Fact Thrift port
  set_fact:  
    zk_port: '{{ zookeeper_port_status.results }}'